// THIS FILE WILL BE OVERWRITTEN BY DEV-C++!
// DO NOT EDIT!

#ifndef SQL2DIAGRAM_PRIVATE_H
#define SQL2DIAGRAM_PRIVATE_H

// VERSION DEFINITIONS
#define VER_STRING	"0.1.1.31"
#define VER_MAJOR	0
#define VER_MINOR	1
#define VER_RELEASE	1
#define VER_BUILD	31
#define COMPANY_NAME	""
#define FILE_VERSION	""
#define FILE_DESCRIPTION	"SQL diagram generator"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"sql2dia"
#define PRODUCT_VERSION	""

#endif //SQL2DIAGRAM_PRIVATE_H
